[
  layers: [
    cli_entrypoints: "Mix.Tasks.*",
    cli_commands: "Reach.CLI.Commands.*",
    cli_render: "Reach.CLI.Render.*",
    cli_support: [
      "Reach.CLI.Project",
      "Reach.CLI.Options",
      "Reach.CLI.Pipe",
      "Reach.CLI.Deprecation",
      "Reach.CLI.Format",
      "Reach.CLI.JSONEnvelope",
      "Reach.CLI.BoxartGraph"
    ],
    cli_analysis_legacy: "Reach.CLI.Analyses.*",
    core: "Reach",
    frontend: "Reach.Frontend.*",
    ir: "Reach.IR.*",
    inspect: "Reach.Inspect.*",
    trace: "Reach.Trace.*",
    check: "Reach.Check.*",
    smell: "Reach.Smell.*",
    analysis: [
      "Reach.ControlFlow",
      "Reach.DataDependence",
      "Reach.ControlDependence",
      "Reach.Dominator",
      "Reach.SystemDependence",
      "Reach.Effects",
      "Reach.HigherOrder"
    ],
    otp: "Reach.OTP.*",
    visualization: "Reach.Visualize.*",
    plugins: ["Reach.Plugin", "Reach.Plugins.*"]
  ],
  forbidden_deps: [
    {:cli_support, :cli_entrypoints},
    {:cli_support, :cli_commands},
    {:cli_support, :cli_analysis_legacy},
    {:cli_render, :cli_entrypoints},
    {:cli_render, :cli_commands},
    {:cli_render, :cli_analysis_legacy},
    {:ir, :cli_entrypoints},
    {:ir, :cli_commands},
    {:ir, :cli_render},
    {:ir, :cli_support},
    {:ir, :cli_analysis_legacy},
    {:frontend, :cli_entrypoints},
    {:frontend, :cli_commands},
    {:frontend, :cli_render},
    {:frontend, :cli_support},
    {:frontend, :cli_analysis_legacy},
    {:analysis, :cli_entrypoints},
    {:analysis, :cli_commands},
    {:analysis, :cli_render},
    {:analysis, :cli_support},
    {:analysis, :cli_analysis_legacy},
    {:trace, :cli_entrypoints},
    {:trace, :cli_commands},
    {:trace, :cli_render},
    {:trace, :cli_support},
    {:trace, :cli_analysis_legacy},
    {:smell, :cli_entrypoints},
    {:smell, :cli_commands},
    {:smell, :cli_render},
    {:smell, :cli_support},
    {:smell, :cli_analysis_legacy},
    {:otp, :cli_entrypoints},
    {:otp, :cli_commands},
    {:otp, :cli_render},
    {:otp, :cli_support},
    {:otp, :cli_analysis_legacy},
    {:visualization, :cli_entrypoints},
    {:visualization, :cli_commands},
    {:visualization, :cli_render},
    {:visualization, :cli_support},
    {:visualization, :cli_analysis_legacy},
    {:plugins, :cli_entrypoints},
    {:plugins, :cli_commands},
    {:plugins, :cli_render},
    {:plugins, :cli_support},
    {:plugins, :cli_analysis_legacy}
  ],
  allowed_effects: [
    {"Reach.IR.*", [:pure, :unknown, :write]},
    {"Reach.ControlFlow", [:pure, :unknown]},
    {"Reach.Dominator", [:pure, :unknown]},
    {"Reach.DataDependence", [:pure, :unknown]},
    {"Reach.ControlDependence", [:pure, :unknown]},
    {"Reach.SystemDependence", [:pure, :unknown]},
    {"Reach.Effects", [:pure, :unknown, :io, :read, :write]},
    {"Reach.CLI.Format", [:pure, :unknown, :io, :read, :write]},
    {"Reach.CLI.Options", [:pure, :unknown]},
    {"Reach.CLI.Pipe", [:pure, :unknown, :write, :io, :exception]}
  ],
  public_api: [],
  internal: [],
  internal_callers: [],
  test_hints: [
    {"lib/reach/visualize/**",
     ["test/visualize/block_quality_test.exs", "test/visualize_test.exs"]},
    {"lib/reach/frontend/**", ["test/ir/frontend_elixir_test.exs", "test/frontend"]},
    {"lib/mix/tasks/**", ["test/mix_task_canonical_test.exs"]},
    {"lib/reach/cli/**", ["test/mix_task_canonical_test.exs"]},
    {"lib/reach/check/**", ["test/mix_task_canonical_test.exs", "test/smell_test.exs"]},
    {"lib/reach/inspect/**", ["test/mix_task_canonical_test.exs"]},
    {"lib/reach/trace/**", ["test/mix_task_canonical_test.exs", "test/query_test.exs"]},
    {"lib/reach/smell/**", ["test/smell_test.exs"]},
    {"lib/reach/otp/**", ["test/reach/otp"]}
  ]
]
